apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cfmp-order
  labels:
    app: notification-service
    tier: backend
    version: v1
spec:
  replicas: 1  # 通知服务默认1个副本
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0    # 通知服务更新时不允许不可用
      maxSurge: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        tier: backend
        version: v1
    spec:
      containers:
      - name: notification-service
        image: notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8003
          name: http
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: DEBUG
          value: "False"
        - name: NACOS_SERVER
          value: "123.57.145.79:8848"
        - name: NACOS_NAMESPACE
          value: "public"
        - name: NACOS_USERNAME
          value: "nacos"
        - name: NACOS_PASSWORD
          value: "nacos"
        - name: NOTIFICATION_DB_HOST
          value: "mysql-service"
        - name: NOTIFICATION_DB_NAME
          value: "cfmp_notification"
        - name: NOTIFICATION_DB_USER
          value: "root"
        - name: NOTIFICATION_DB_PASSWORD
          value: "root123"
        - name: NOTIFICATION_DB_PORT
          value: "3306"
        # 通知服务配置
        - name: ENABLE_CIRCUIT_BREAKER
          value: "true"
        - name: USER_SERVICE_TIMEOUT
          value: "5"
        - name: NOTIFICATION_BATCH_SIZE
          value: "100"
        - name: GRACEFUL_DEGRADATION
          value: "true"
        - name: NODE_PORT
          value: "30003"
        - name: NODE_IP
          value: "101.200.231.225"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cfmp-order
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  type: NodePort
  ports:
  - name: http
    port: 8003
    targetPort: 8003
    nodePort: 30003
