apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cfmp-order
  labels:
    app: order-service
    tier: backend
    version: v1
spec:
  replicas: 2  # 默认2个副本，将由HPA管理
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
        tier: backend
        version: v1
    spec:
      affinity:
        # Pod反亲和性：避免同一节点运行过多相同服务
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - order-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: DEBUG
          value: "False"
        - name: NACOS_SERVER
          value: "123.57.145.79:8848"
        - name: NACOS_NAMESPACE
          value: "public"
        - name: NACOS_USERNAME
          value: "nacos"
        - name: NACOS_PASSWORD
          value: "nacos"
        - name: ORDER_DB_HOST
          value: "mysql-service"
        - name: ORDER_DB_NAME
          value: "cfmp_order"
        - name: ORDER_DB_USER
          value: "root"
        - name: ORDER_DB_PASSWORD
          value: "root123"
        - name: ORDER_DB_PORT
          value: "3306"
        # 降级功能环境变量
        - name: ENABLE_CIRCUIT_BREAKER
          value: "true"
        - name: PAYMENT_SERVICE_TIMEOUT
          value: "10"
        - name: NOTIFICATION_SERVICE_TIMEOUT
          value: "5"
        - name: PRODUCT_SERVICE_TIMEOUT
          value: "8"
        - name: NODE_PORT
          value: "30001"
        - name: NODE_IP
          value: "101.200.231.225"

        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cfmp-order
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  type: NodePort
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    nodePort: 30001
