apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cfmp-order
  labels:
    app: payment-service
    tier: backend
    version: v1
spec:
  replicas: 1  # 支付服务默认1个副本，降低基础负担
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1    # 支付服务更新时最多允许1个不可用
      maxSurge: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        tier: backend
        version: v1
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - payment-service
              topologyKey: kubernetes.io/hostname
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
          name: http
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: DEBUG
          value: "False"
        - name: NACOS_SERVER
          value: "123.57.145.79:8848"
        - name: NACOS_NAMESPACE
          value: "public"
        - name: NACOS_USERNAME
          value: "nacos"
        - name: NACOS_PASSWORD
          value: "nacos"
        - name: PAYMENT_DB_HOST
          value: "mysql-service"
        - name: PAYMENT_DB_NAME
          value: "cfmp_payment"
        - name: PAYMENT_DB_USER
          value: "root"
        - name: PAYMENT_DB_PASSWORD
          value: "root123"
        - name: PAYMENT_DB_PORT
          value: "3306"
        # 支付服务特殊配置
        - name: ENABLE_CIRCUIT_BREAKER
          value: "true"
        - name: ORDER_SERVICE_TIMEOUT
          value: "15"
        - name: NOTIFICATION_SERVICE_TIMEOUT
          value: "5"
        - name: PAYMENT_RETRY_COUNT
          value: "3"
        - name: PAYMENT_TIMEOUT
          value: "30"
        - name: NODE_PORT
          value: "30002"
        - name: NODE_IP
          value: "101.200.231.225"
        resources:
          requests:
            memory: "512Mi"  # 支付服务需要更多内存
            cpu: "300m"
          limits:
            memory: "1.5Gi"
            cpu: "1500m"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cfmp-order
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  type: NodePort
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    nodePort: 30002
