apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cfmp-order
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: IfNotPresent  # 允许从镜像仓库拉取
        ports:
        - containerPort: 8002
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "config.settings"
        - name: DEBUG
          value: "False"
        - name: NACOS_SERVER
          value: "123.57.145.79:8848"
        - name: NACOS_NAMESPACE
          value: "public"
        - name: NACOS_USERNAME
          value: "nacos"
        - name: NACOS_PASSWORD
          value: "nacos"
        - name: PAYMENT_DB_HOST
          value: "mysql-service"
        - name: PAYMENT_DB_NAME
          value: "cfmp_payment"
        - name: PAYMENT_DB_USER
          value: "root"
        - name: PAYMENT_DB_PASSWORD
          value: "root123"
        - name: PAYMENT_DB_PORT
          value: "3306"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health/
            port: 8002
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health/
            port: 8002
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: cfmp-order
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  type: NodePort
  ports:
  - name: http
    port: 8002
    targetPort: 8002
    nodePort: 30002
