# Generated by Django 5.2 on 2025-09-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
